/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#e6f6ff",
        "primary-fixed-dim": "#a2c9ff",
        "surface-bright": "#f3faff",
        "surface-variant": "#cfe6f2",
        "on-primary": "#ffffff",
        "secondary": "#2a6b2c",
        "primary-fixed": "#d3e4ff",
        "on-surface": "#071e27",
        "surface-dim": "#c7dde9",
        "on-background": "#071e27",
        "outline": "#727782",
        "on-primary-fixed": "#001c38",
        "on-primary-container": "#b1d1ff",
        "inverse-on-surface": "#dff4ff",
        "background": "#f3faff",
        "primary-container": "#005a9e",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#91d78a",
        "secondary-fixed": "#acf4a4",
        "tertiary-fixed": "#97f3e2",
        "primary": "#004277",
        "on-secondary-fixed-variant": "#0c5216",
        "tertiary": "#004a41",
        "on-tertiary-container": "#83e0ce",
        "surface": "#f3faff",
        "inverse-primary": "#a2c9ff",
        "tertiary-container": "#006458",
        "on-surface-variant": "#414750",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#00201b",
        "on-tertiary-fixed-variant": "#005047",
        "on-primary-fixed-variant": "#004881",
        "surface-container-highest": "#cfe6f2",
        "error-container": "#ffdad6",
        "surface-container-high": "#d5ecf8",
        "surface-container": "#dbf1fe",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#7ad7c6",
        "on-secondary-fixed": "#002203",
        "surface-tint": "#1260a5",
        "outline-variant": "#c1c7d2",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#307231",
        "inverse-surface": "#1e333c",
        "secondary-container": "#acf4a4"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
