import React from "react";
import { Link } from "react-router-dom";

export default function Disclaimer() {
  return (
    <main className="max-w-7xl mx-auto px-6 py-16 md:py-24">
      {/* Hero Section */}
      <header className="mb-16">
        <div className="inline-block px-3 py-1 mb-6 rounded-full bg-surface-container text-primary font-label text-xs font-semibold tracking-wider uppercase">
          Legal Notice
        </div>
        <h1 className="text-5xl md:text-6xl font-extrabold text-primary tracking-[-0.03em] leading-tight mb-6">
          Disclaimer &amp; <br /><span className="text-secondary">Terms of Use</span>
        </h1>
        <p className="text-lg text-on-surface-variant max-w-2xl font-body leading-relaxed">
          Last Updated: March 21, 2026. Please read this disclaimer carefully before using any tools or calculators provided by FinTools India.
        </p>
      </header>

      {/* Bento Grid Layout for Legal Sections */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        {/* Primary Warning Card */}
        <div className="md:col-span-8 bg-surface-container-low p-8 md:p-12 rounded-[2rem] border border-outline-variant/15 flex flex-col justify-center">
          <div className="flex items-start gap-6">
            <div className="w-16 h-16 rounded-xl bg-error-container flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-error text-3xl">warning</span>
            </div>
            <div>
              <h2 className="text-2xl font-bold text-on-surface mb-4">Educational Purposes Only</h2>
              <p className="text-on-surface-variant leading-relaxed mb-6 font-body">
                The financial calculators, projections, and data analysis tools provided on this platform are designed for <strong>illustrative and educational purposes only</strong>. The figures shown are estimates based on user input and historical averages which may not reflect future performance.
              </p>
              <div className="p-6 bg-surface-container-lowest rounded-xl border-l-4 border-secondary">
                <p className="text-on-surface italic font-body">
                  "Calculations generated by FinTools India do not constitute a guarantee of future outcomes, investment returns, or tax savings."
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Side Metric/Action Card */}
        <div className="md:col-span-4 bg-primary text-on-primary p-8 rounded-[2rem] flex flex-col justify-between overflow-hidden relative">
          <div className="relative z-10">
            <h3 className="text-xl font-bold mb-4">Need Advice?</h3>
            <p className="text-primary-fixed/80 text-sm leading-relaxed mb-8">
              For specific financial planning or investment decisions, always consult with a SEBI Registered Investment Advisor (RIA).
            </p>
            <Link className="inline-flex items-center gap-2 text-on-primary font-bold hover:gap-3 transition-all" to="/contact">
              Find a Professional <span className="material-symbols-outlined">arrow_forward</span>
            </Link>
          </div>
          <div className="absolute -bottom-10 -right-10 opacity-10">
            <span className="material-symbols-outlined text-[180px]">account_balance</span>
          </div>
        </div>

        {/* Professional Advice Detail */}
        <div className="md:col-span-4 bg-surface-container p-8 rounded-[2rem]">
          <span className="material-symbols-outlined text-primary mb-4">gavel</span>
          <h3 className="text-lg font-bold text-on-surface mb-2">No Substitute for Advice</h3>
          <p className="text-sm text-on-surface-variant leading-relaxed font-body">
            We are not a brokerage firm, law firm, or tax advisory service. Use of our tools does not create a client-advisor relationship between you and FinTools India.
          </p>
        </div>

        {/* Accuracy Disclaimer */}
        <div className="md:col-span-4 bg-surface-container p-8 rounded-[2rem]">
          <span className="material-symbols-outlined text-primary mb-4">precision_manufacturing</span>
          <h3 className="text-lg font-bold text-on-surface mb-2">Accuracy of Information</h3>
          <p className="text-sm text-on-surface-variant leading-relaxed font-body">
            While we strive for technical accuracy, financial markets and tax laws in India are subject to rapid change. We do not warrant that calculations are error-free or current.
          </p>
        </div>

        {/* Risk Disclosure */}
        <div className="md:col-span-4 bg-surface-container p-8 rounded-[2rem]">
          <span className="material-symbols-outlined text-primary mb-4">trending_down</span>
          <h3 className="text-lg font-bold text-on-surface mb-2">Investment Risks</h3>
          <p className="text-sm text-on-surface-variant leading-relaxed font-body">
            Investment in securities market are subject to market risks. Read all the related documents carefully before investing. Past performance is not indicative of future results.
          </p>
        </div>

        {/* Expanded Legal Text Section */}
        <div className="md:col-span-12 mt-12 space-y-12">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <section>
              <h4 className="text-xs font-bold uppercase tracking-widest text-primary mb-6 flex items-center gap-2">
                <span className="w-8 h-px bg-primary/30"></span> Limitation of Liability
              </h4>
              <div className="space-y-4 text-on-surface-variant text-sm leading-relaxed font-body">
                <p>FinTools India, its founders, and employees shall not be held liable for any financial losses, damages, or missed opportunities resulting from the use or reliance upon our software, data, or content.</p>
                <p>The user assumes full responsibility for any financial decisions made based on the output of these tools. We strongly recommend independent verification of all results with official financial statements or professional consultants.</p>
              </div>
            </section>
            <section>
              <h4 className="text-xs font-bold uppercase tracking-widest text-primary mb-6 flex items-center gap-2">
                <span className="w-8 h-px bg-primary/30"></span> Third-Party Links
              </h4>
              <div className="space-y-4 text-on-surface-variant text-sm leading-relaxed font-body">
                <p>Our tools may reference or link to third-party financial products, platforms, or articles. Such references do not imply endorsement, and we are not responsible for the accuracy or practices of these external entities.</p>
                <p>Always review the specific terms and conditions and disclaimers of any third-party financial service before proceeding with transactions.</p>
              </div>
            </section>
          </div>
        </div>
      </div>

      {/* Contact/Help Section */}
      <section className="mt-24 p-12 bg-surface-container-high rounded-[3rem] text-center">
        <h2 className="text-2xl font-bold text-primary mb-4">Questions regarding this disclaimer?</h2>
        <p className="text-on-surface-variant mb-8 max-w-xl mx-auto">If you need further clarification on how our tools work or the limitations of our projections, please contact our legal compliance team.</p>
        <div className="flex flex-wrap justify-center gap-4">
          <Link to="/contact" className="bg-primary text-on-primary px-8 py-3 rounded-xl font-bold transition-all hover:scale-95 inline-block">
            Contact Legal Team
          </Link>
          <Link to="/help-center" className="bg-surface-container-lowest text-primary px-8 py-3 rounded-xl font-bold border border-outline-variant/15 transition-all hover:bg-surface-container inline-block">
            View FAQ
          </Link>
        </div>
      </section>
    </main>
  );
}
